name             'kafka'
description      'Install and configure kafka'
maintainer       'Heavy Water Operations, LLC'
maintainer_email 'helpdesk@heavywater.io'
license          'Apache-2.0'
version          '0.2.8'
source_url       'https://github.com/hw-cookbooks/kafka'
issues_url       'https://github.com/hw-cookbooks/kafka/issues'

supports 'debian'
supports 'redhat'

depends 'java',  '>= 1.11.4'
depends 'runit', '>= 1.1.4'
depends 'builder', '>= 0.1.1'
depends 'zookeeperd', '>= 0.1.0'
depends 'ark'
